#JPA
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swus?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
##        dialect: org.hibernate.dialect.PostgreSQLDialect
##        default_batch_fetch_size: 100
logging:
  file:
    path: /Users/Logs/swus-spring
  level:
    root: info
    com.ssaky.swus: debug
swagger:
  paths: |
    /swagger-ui/**,
    /webjars/springfox-swagger-ui/**/*,
    /swagger-resources,
    /swagger-resources/**/*,
    /v2/api-docs